inc-7 Добавлено конфигурирование сервиса с помощью флагов командной строки
slavkluev/praktikum-shortener pull request #7
Opened 2022-01-25 11:21 UTC by slavkluev

2022-01-25 14:28 UTC, Bazys requested changes
Предлагаю на считывать с диска каждый раз при запросе УРЛ. 
А использовать мапу в памяти. И уже при старте приложение читать с диска в мапу данные, а при остановке - записывать

2022-01-25 14:28 UTC, Bazys commented on internal/app/storages/file_storage.go
> +	for scanner.Scan() {
а точно надо читать каждый раз с диска?
может при старте приложения читаем из диска, при завершении (в том числе аварийном, через defer) записываем, а в принципе храним в памяти. Ну и для своего успокоения можно  каждые n минут сохранять на диск в отдельной горутинке.

2022-01-25 14:28 UTC, Bazys commented on internal/app/storages/simple_storage.go
> +type SimpleStorage struct {
может есть смысл совместить эти два хранилища?

2022-01-25 19:17 UTC, slavkluev commented on internal/app/storages/file_storage.go
> +	for scanner.Scan() {
Нет, конечно, каждый раз читать с диска не стоит)
Идея с горутиной мне очень понравилась 👍

2022-01-25 20:22 UTC, slavkluev commented on internal/app/handlers/api_shorten_url_test.go
> +	file, err := ioutil.TempFile("", "db")
Я сделал здесь нечто некрасивое)
Как лучше тестировать в таких случаях? Может лучше было бы оставить простой storage, чтобы handlers протестировать. А storage, который с файлом взаимодействует, отдельно покрывать?

2022-01-26 16:04 UTC, Bazys commented on internal/app/handlers/api_shorten_url_test.go
> +	file, err := ioutil.TempFile("", "db")
я никогда не добиваюсь красоты тестов.
Конкретно тесты должны проверять работоспособность, а если при этом течет память или еще что-то, то ну и пусть. Тесты выполнились и мы пошли дальше.

2022-01-26 16:15 UTC, Bazys requested changes

2022-01-26 16:15 UTC, Bazys commented on internal/app/storages/simple_storage.go
> +	err := s.writeRecordToFile(Record{
Это пропустил или еще не дошли руки?
Писать тоже не стоит при каждом новом

2022-01-27 13:08 UTC, slavkluev commented on internal/app/storages/simple_storage.go
> +	err := s.writeRecordToFile(Record{
Если не писать при каждом новом, то тесты не проходят в 6 и 7 инкрементах: "Файл с сохраненными URL не должен быть пуст"

2022-01-28 15:44 UTC, Bazys approved these changes

2022-01-29 18:23 UTC, merged